 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container rinha-pg  Creating
 Container rinha-pg  Created
 Container rizzo-nodejs-api03-1  Creating
 Container rizzo-nodejs-api01-1  Creating
 Container rizzo-nodejs-api02-1  Creating
 Container rizzo-nodejs-api01-1  Created
 Container rizzo-nodejs-api02-1  Created
 Container rizzo-nodejs-api03-1  Created
 Container rizzo-nodejs-nginx-1  Creating
 Container rizzo-nodejs-nginx-1  Created
Attaching to rinha-pg, api01-1, api02-1, api03-1, nginx-1
rinha-pg  | The files belonging to this database system will be owned by user "postgres".
rinha-pg  | This user must also own the server process.
rinha-pg  | 
rinha-pg  | The database cluster will be initialized with locale "en_US.utf8".
rinha-pg  | The default database encoding has accordingly been set to "UTF8".
rinha-pg  | The default text search configuration will be set to "english".
rinha-pg  | 
rinha-pg  | Data page checksums are disabled.
rinha-pg  | 
rinha-pg  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
rinha-pg  | creating subdirectories ... ok
rinha-pg  | selecting dynamic shared memory implementation ... posix
rinha-pg  | selecting default max_connections ... 100
rinha-pg  | selecting default shared_buffers ... 128MB
rinha-pg  | selecting default time zone ... Etc/UTC
rinha-pg  | creating configuration files ... ok
api03-1   | yarn run v1.22.19
api03-1   | $ prisma migrate deploy && prisma db seed
api02-1   | yarn run v1.22.19
api02-1   | $ prisma migrate deploy && prisma db seed
rinha-pg  | running bootstrap script ... ok
api01-1   | yarn run v1.22.19
api01-1   | $ prisma migrate deploy && prisma db seed
nginx-1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1   | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1   | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1   | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1   | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1   | 2024/02/15 14:55:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:55:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:55:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:55:40 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinha-pg  | performing post-bootstrap initialization ... ok
nginx-1   | 2024/02/15 14:55:42 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinha-pg  | syncing data to disk ... ok
rinha-pg  | 
rinha-pg  | 
rinha-pg  | Success. You can now start the database server using:
rinha-pg  | 
rinha-pg  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
rinha-pg  | 
rinha-pg  | initdb: warning: enabling "trust" authentication for local connections
rinha-pg  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
rinha-pg  | waiting for server to start....2024-02-15 14:55:43.233 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rinha-pg  | 2024-02-15 14:55:43.299 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rinha-pg  | 2024-02-15 14:55:43.315 UTC [52] LOG:  database system was shut down at 2024-02-15 14:55:40 UTC
rinha-pg  | 2024-02-15 14:55:43.322 UTC [49] LOG:  database system is ready to accept connections
rinha-pg  |  done
rinha-pg  | server started
api02-1   | Environment variables loaded from .env
api02-1   | Prisma schema loaded from prisma/schema.prisma
api03-1   | Environment variables loaded from .env
api03-1   | Prisma schema loaded from prisma/schema.prisma
api02-1   | Datasource "db": PostgreSQL database "rinha", schema "public" at "db-rinha:5432"
api03-1   | Datasource "db": PostgreSQL database "rinha", schema "public" at "db-rinha:5432"
api01-1   | Environment variables loaded from .env
api01-1   | Prisma schema loaded from prisma/schema.prisma
api01-1   | Datasource "db": PostgreSQL database "rinha", schema "public" at "db-rinha:5432"
rinha-pg  | CREATE DATABASE
rinha-pg  | 
rinha-pg  | 
rinha-pg  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
rinha-pg  | 
rinha-pg  | 2024-02-15 14:55:44.307 UTC [49] LOG:  received fast shutdown request
rinha-pg  | waiting for server to shut down....2024-02-15 14:55:44.310 UTC [49] LOG:  aborting any active transactions
rinha-pg  | 2024-02-15 14:55:44.315 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
rinha-pg  | 2024-02-15 14:55:44.394 UTC [50] LOG:  shutting down
rinha-pg  | 2024-02-15 14:55:44.404 UTC [50] LOG:  checkpoint starting: shutdown immediate
api02-1   | 
api02-1   | Error: P1001: Can't reach database server at `db-rinha`:`5432`
api02-1   | 
api02-1   | Please make sure your database server is running at `db-rinha`:`5432`.
api03-1   | 
api03-1   | Error: P1001: Can't reach database server at `db-rinha`:`5432`
api03-1   | 
api03-1   | Please make sure your database server is running at `db-rinha`:`5432`.
api01-1   | 
api01-1   | Error: P1001: Can't reach database server at `db-rinha`:`5432`
api01-1   | 
api01-1   | Please make sure your database server is running at `db-rinha`:`5432`.
nginx-1   | 2024/02/15 14:55:44 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinha-pg  | 2024-02-15 14:55:44.745 UTC [50] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.157 s, sync=0.171 s, total=0.351 s; sync files=301, longest=0.006 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913070, redo lsn=0/1913070
rinha-pg  | 2024-02-15 14:55:44.754 UTC [49] LOG:  database system is shut down
rinha-pg  |  done
rinha-pg  | server stopped
rinha-pg  | 
rinha-pg  | PostgreSQL init process complete; ready for start up.
rinha-pg  | 
rinha-pg  | 2024-02-15 14:55:44.917 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rinha-pg  | 2024-02-15 14:55:44.917 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
rinha-pg  | 2024-02-15 14:55:44.917 UTC [1] LOG:  listening on IPv6 address "::", port 5432
rinha-pg  | 2024-02-15 14:55:44.926 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rinha-pg  | 2024-02-15 14:55:44.939 UTC [65] LOG:  database system was shut down at 2024-02-15 14:55:44 UTC
rinha-pg  | 2024-02-15 14:55:44.997 UTC [1] LOG:  database system is ready to accept connections
api01-1   | error Command failed with exit code 1.
api01-1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api03-1   | error Command failed with exit code 1.
api03-1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api02-1   | error Command failed with exit code 1.
api02-1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api01-1 exited with code 1
api02-1 exited with code 1
api03-1 exited with code 1
nginx-1   | 2024/02/15 14:55:46 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:55:48 [error] 29#29: *9 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:56:25 [error] 29#29: *10 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:56:43 [error] 29#29: *10 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:02 [error] 29#29: *10 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:07 [error] 29#29: *14 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:10 [error] 29#29: *14 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:10 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:12 [error] 29#29: *17 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:17 [error] 29#29: *18 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:17 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:22 [error] 29#29: *20 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:25 [error] 29#29: *20 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:25 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:27 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:32 [error] 29#29: *24 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:32 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:37 [error] 29#29: *26 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:40 [error] 29#29: *26 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:40 [error] 29#29: *26 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:42 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:47 [error] 29#29: *30 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:47 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:52 [error] 29#29: *32 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:56 [error] 29#29: *32 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:57:56 [error] 29#29: *32 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:58:01 [error] 29#29: *35 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:58:01 [error] 29#29: *35 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:58:06 [error] 29#29: *37 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.64.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/15 14:58:06 [error] 29#29: *37 no live upstreams while connecting to upstream, client: 192.168.64.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
rinha-pg  | 2024-02-15 14:58:11.743 UTC [1] LOG:  received fast shutdown request
rinha-pg  | 2024-02-15 14:58:11.830 UTC [1] LOG:  aborting any active transactions
rinha-pg  | 2024-02-15 14:58:11.833 UTC [1] LOG:  background worker "logical replication launcher" (PID 68) exited with exit code 1
rinha-pg  | 2024-02-15 14:58:11.833 UTC [63] LOG:  shutting down
rinha-pg  | 2024-02-15 14:58:11.835 UTC [63] LOG:  checkpoint starting: shutdown immediate
rinha-pg  | 2024-02-15 14:58:12.356 UTC [63] LOG:  checkpoint complete: wrote 30 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.091 s, sync=0.214 s, total=0.523 s; sync files=11, longest=0.212 s, average=0.020 s; distance=132 kB, estimate=132 kB; lsn=0/1934258, redo lsn=0/1934258
rinha-pg  | 2024-02-15 14:58:12.361 UTC [1] LOG:  database system is shut down
rinha-pg exited with code 0
